### ISSUE TITLE
Doesn't seem to be compatible with MAC

### ISSUE THREAD

**Issue by J-SUPHA** [xingyaoww/mint-bench#1]
I ran the command ```pip3 install -e .``` 

Then I realized that there is no support for MAC given by the following error. Was wondering if there is a way to run mint-bench on MAC/ARM architecture ? Is there plans to do this. Would be down to collaborate on this.

```
error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [91 lines of output]
      /Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      + echo 'Running setup.sh...'
      Running setup.sh...
      ++ uname -s
      + unameOut=Darwin
      + case "${unameOut}" in
      + machine=Mac
      + cd textworld/thirdparty/
      + '[' '!' -e I7_6M62_Linux_all.tar.gz ']'
      + echo 'Downloading Inform7 CLI'
      Downloading Inform7 CLI
      + curl -LO http://emshort.com/inform-app-archive/6M62/I7_6M62_Linux_all.tar.gz
        % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                       Dload  Upload   Total   Spent    Left  Speed
      
        0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       85 22.1M   85 18.8M    0     0  43.9M      0 --:--:-- --:--:-- --:--:-- 44.2M
      100 22.1M  100 22.1M    0     0  46.6M      0 --:--:-- --:--:-- --:--:-- 46.9M
      + '[' Mac == Mac ']'
      + '[' '!' -e I7-6M62-OSX-Interim.dmg ']'
      + echo 'Downloading Inform7 for Mac'
      Downloading Inform7 for Mac
      + curl -LO http://emshort.com/inform-app-archive/6M62/I7-6M62-OSX-Interim.dmg
        % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                       Dload  Upload   Total   Spent    Left  Speed
      
        0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       74 36.8M   74 27.2M    0     0  29.0M      0  0:00:01 --:--:--  0:00:01 29.2M
      100 36.8M  100 36.8M    0     0  31.5M      0  0:00:01  0:00:01 --:--:-- 31.7M
      + '[' '!' -d inform7-6M62 ']'
      + tar xf I7_6M62_Linux_all.tar.gz
      + echo 'Installing Inform7 CLI'
      Installing Inform7 CLI
      + cd inform7-6M62/
      + ./install-inform7.sh --prefix /private/var/folders/rp/grn6fms90dg9rm3dxm1tqgk40000gn/T/pip-install-s9wth87j/textworld_b90037e341714df4a9330b06b4c7d6e4/textworld/thirdparty/inform7-6M62
      You should have the executable compilers for the arm64 architecture.
      Giving up!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rp/grn6fms90dg9rm3dxm1tqgk40000gn/T/pip-install-s9wth87j/textworld_b90037e341714df4a9330b06b4c7d6e4/setup.py", line 41, in <module>
          setup(
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/j-supha/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/rp/grn6fms90dg9rm3dxm1tqgk40000gn/T/pip-install-s9wth87j/textworld_b90037e341714df4a9330b06b4c7d6e4/setup.py", line 37, in run
          _pre_install(None)
        File "/private/var/folders/rp/grn6fms90dg9rm3dxm1tqgk40000gn/T/pip-install-s9wth87j/textworld_b90037e341714df4a9330b06b4c7d6e4/setup.py", line 18, in _pre_install
          check_call(['./setup.sh'], shell=True, cwd=os.getcwd())
        File "/Users/j-supha/miniconda3/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./setup.sh']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for textworld
  Running setup.py clean for textworld
  Building wheel for visdom (setup.py) ... done
  Created wheel for visdom: filename=visdom-0.2.4-py3-none-any.whl size=1408197 sha256=e05a476b3633f3bd89b371f69de5a38ed0be3991c4e1e36ea6e30fa520994ae5
  Stored in directory: /Users/j-supha/Library/Caches/pip/wheels/fa/a4/bb/2be445c295d88a74f9c0a4232f04860ca489a5c7c57eb959d9
  Building wheel for wikipedia (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11680 sha256=c32ca94f335f7d01e998247970528c775b1abec6b21be0fd495c761e6ef276dc
  Stored in directory: /Users/j-supha/Library/Caches/pip/wheels/8f/ab/cb/45ccc40522d3a1c41e1d2ad53b8f33a62f394011ec38cd71c6
  Building wheel for jericho (setup.py) ... done
  Created wheel for jericho: filename=jericho-3.1.2-py3-none-any.whl size=278756 sha256=3b7c626bd874c5ff10f889b2ef2aa90adb7f69ecb7d48e696665dd08f53d49b3
  Stored in directory: /Users/j-supha/Library/Caches/pip/wheels/8a/10/2c/903e6352f8c4542acfc60b0505d230fd5e8d61222c2c6394c1
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13705 sha256=98be2f94778c861c04d305695b7420f7f0d60e8d232a6c1298912b01c5d882c3
  Stored in directory: /Users/j-supha/Library/Caches/pip/wheels/1a/b0/8c/4b75c4116c31f83c8f9f047231251e13cc74481cca4a78a9ce
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492025 sha256=04813242dac1ab1dfe21baab30fbabfb6ab1525910c9a042b10dede75278e1dc
  Stored in directory: /Users/j-supha/Library/Caches/pip/wheels/da/19/ca/9d8c44cd311a955509d7e13da3f0bea42400c469ef825b580b
Successfully built gym pandas alfworld fast-downward visdom wikipedia jericho docopt future
Failed to build textworld
ERROR: Could not build wheels for textworld, which is required to install pyproject.toml-based projects
```

**Comment by xingyaoww** [comment]
Thank you for your interest! 

I guess the issue you are running into is probably caused by the version of [textworld](https://github.com/microsoft/TextWorld) used by ALFWorld (textworld @ https://github.com/MarcCote/TextWorld/archive/handcoded_expert_integration.zip) is in-compatible with MacOS.

Maybe an easy workaround would be [running our provided docker container (with all environments set up) on ARM MacOS](https://docs.docker.com/desktop/install/mac-install/) -- although it will be slower since it is not complied for arm. Or, if you want to skip the evaluation of ALFWorld, you can also remove these (ALFWorld-related) dependencies that cause errors from `requirements.txt`
